title: Joshua Ross
baseURL: https://rossjm.dev
paginate: 5
theme: [PaperMod]
min_version: "0.134.0"


enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

params:
  author:
    - Joshua Ross
  mainSections:
    - docs
    - posts
  disableAnchoredHeadings: true
  DateFormat: "2006-01-02"
  useCustomAnalytics: true
  defaultTheme: profile
  ShowShareButtons: false
  ShowReadingTime: true
  ShowWordCount: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: false
  EnableInstantClick: true
  EnableImageZoom: true


  profileMode:
    enabled: true
    title: Joshua Ross
    imageUrl: /img/me.jpg
    # imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    subtitle: ☁️ DevOps Nerd
    buttons:
      - name: About Me
        url: about
      - name: Blog
        url: posts
      - name: Resume
        url: resume

  socialIcons:
    - name: github
      url: "https://github.com/coloredbytes/"
    - name: linkedin
      url: "https://www.linkedin.com/in/joshuamalcom/"
    - name: email
      url: "mailto:contact@rossjm.dev"
  
  assets:
    disableHLJS: true 
    favicon: "assets/favicon.ico"
    

minify:
  disableXML: true
  # minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: true
